# Generated by Django 2.2.5 on 2021-02-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20210223_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Aminites'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='houserule',
            options={'verbose_name': 'House Rule'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['created'], 'verbose_name': 'Room Type'},
        ),
        migrations.RenameField(
            model_name='amenity',
            old_name='cerated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='cerated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='houserule',
            old_name='cerated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='cerated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='roomtype',
            old_name='cerated',
            new_name='created',
        ),
    ]
