# Generated by Django 2.2.5 on 2021-02-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pendig', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pendig', max_length=12),
        ),
    ]
