# Generated by Django 2.2.5 on 2021-04-06 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_bookedday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookedDay',
        ),
    ]
